# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 487d51c749c9f87c3eca10e54c130d9f79ccdb47466d6a544a19b249e27d75d88b897a0fe26f010035c08b447cda771f1409d841f3c55fa88eef0548c2443410

test:
  secret_key_base: 388d01780d454339420f1a1ec05e1c0dda98dcacd322de65e66694791a4fda1e1c1ccf0987f021b49315316d51e15ac09a7403b45e613459aa2b7af27fbced77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
